#!/bin/bash
if [ -z "$1" ]; then
    label='haldane'
else
    label=$1
fi
if [ -z "$2" ]; then
    fsize=100
else
    fsize=$2
fi

xoff=280
yoff=100
xoff2=140
yoff2=130

distance=Euclidean
#font=RocketScript
font=Bookman-DemiItalic
#distance=Chebyshev       
#font=Courier
labu=${label^}

# Must duplicate size of platebglong.png (1172x1757) to combine images
convert -size 1172x1757 xc:black -font $font -pointsize ${fsize} \
           -fill \#7788DD -annotate +$xoff+$yoff $labu \
          -gamma 2  +level 0,1000 -white-threshold 999 \
          -morphology Distance $distance:4,3000 -auto-level \
          -shade 135x30 -auto-level +level 10,90% outA.png
composite -compose Multiply outA.png platebglong.png $1_x.png
convert -level 0,50% $1_x.png $1.png

