#!/bin/bash
template="platebglong.png"

if [ -z "$1" ]; then
    label='haldane'
else
    label=$1
fi
if [ -z "$2" ]; then
    fsize=100
else
    fsize=$2
fi


twidth=`identify -format "%[fx:w]" $template`
theight=`identify -format "%[fx:h]" $template`
xoff=$(($twidth/2-280))
yoff=100
distance=Euclidean
font=Bookman-DemiItalic
labu=${label^}

# Must duplicate size of platebglong.png (1172x1757) to combine images
convert -size $twidth"x"$theight xc:black -font $font -pointsize ${fsize} \
           -fill \#7788DD -annotate +$xoff+$yoff $labu \
          -gamma 2  +level 0,1000 -white-threshold 999 \
          -morphology Distance $distance:4,3000 -auto-level \
          -shade 135x30 -auto-level +level 10,90% outA.png
composite -compose Multiply outA.png platebglong.png $1_x.png
convert -level 0,50% $1_x.png $1.png

