#!/bin/bash
if [ -z "$1" ]; then
    label='darwin'
else
    label=$1
fi
if [ -z "$2" ]; then
    fsize=128;
else fsize=$2;
fi
yoff=140
yoff2=130
       
labu=${label^}
convert -size 580x170 canvas:none -font Bookman-DemiItalic -pointsize ${fsize} -draw "text 80,$yoff $labu" -channel RGBA -blur 0x6 -fill \#99AADD -stroke \#4444FF -draw "text 90,$yoff2 $labu" outA.png
/usr/bin/composite -compose Dst_In outA.png smallbluebrush.jpg -matte $1.png


